context:
  version: "7.2.1"

package:
  name: ugrep
  version: ${{ version }}

source:
  url: https://github.com/Genivia/ugrep/archive/v${{ version }}.tar.gz
  sha256: 10130417e265582fc35a5356305b308027fd8ed186b8cbb1399c1b8e530ce899

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - m4
    - make
    - pkg-config
  host:
    - brotli
    - bzip2
    - bzip3
    - libtool
    - lz4-c
    - pcre2
    - xz
    - zstd
    - zlib

tests:
  - script:
      - ugrep --version

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Ultra fast grep with query UI, fuzzy search, archive search, and more
  homepage: https://github.com/Genivia/ugrep
  repository: https://github.com/Genivia/ugrep

extra:
  recipe-maintainers:
    - danielnachun
