context:
  version: 6.1.0

package:
  name: ugrep
  version: ${{ version }}

source:
  url: https://github.com/Genivia/ugrep/archive/v${{ version }}.tar.gz
  sha256: 587ebb694dd3d2f5bef9f35df5b9e196b89da981cfe1084539e55b8d9a62fd65

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - brotli
    - bzip2
    - bzip3
    - lz4-c
    - pcre2
    - xz
    - zstd
    - zlib
  ignore_run_exports:
    - brotli
    - libbrotlicommon
    - libbrotlienc

tests:
  - script:
      - ugrep --version

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Ultra fast grep with query UI, fuzzy search, archive search, and more
  home: https://github.com/Genivia/ugrep
  homepage: https://github.com/Genivia/ugrep

extra:
  recipe-maintainers:
    - danielnachun
